development:
  clients:
    default:
      database: gym_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: gym_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= Rails.application.secrets.mongo_uri %>
      options:
        ssl: true
        ssl_verify: false
  options: